name: Daily Index Report

on:
  schedule:
    # Run every weekday at 08:00 Vilnius time (05:00 UTC)
    - cron: '0 5 * * 1-5'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance

      - name: Run index tracker
        run: |
          python tracker.py

      - name: Prepare email subject
        id: subject
        run: |
          echo "SUBJECT=Daily Index Update — $(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Send email (Gmail via connection_url)
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: "smtps://${{ secrets.EMAIL_USER }}:${{ secrets.EMAIL_PASS }}@smtp.gmail.com:465"
          subject: ${{ env.SUBJECT }}
          to: ${{ secrets.EMAIL_TO }}
          from: "Index Tracker <${{ secrets.EMAIL_USER }}>"
          html_body: file://report.html
