name: Daily Index Report

on:
  schedule:
    # 08:00 Vilnius time ≈ 05:00 UTC
    - cron: '0 5 * * 1-5'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tracker
        id: run_script
        run: |
          python tracker.py > output.txt
          echo "OUTPUT<<EOF" >> $GITHUB_ENV
          cat output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Prepare email subject
        id: subject
        run: |
          echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "${{ env.TODAY }} index update"
          to: ${{ secrets.EMAIL_TO }}
          from: "Index Tracker"
          body: ${{ env.OUTPUT }}
